name: Build

on:
  push:
    branches: [ main, test-ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle.kts', 'buildSrc/**', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-
    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew clean check publishToIntegrationRepository --stacktrace
    - uses: actions/upload-artifact@v2
      with:
        name: integration-repository
        path: build/repos/integration

  integration:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        kotlin: [ 1.3.72, 1.4.31, 1.5.0-M1 ]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Disable autocrlf
      run: | 
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle.kts', 'buildSrc/**', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-
    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x gradlew
    - uses: actions/download-artifact@v2
      with:
        name: integration-repository
        path: build/repos/integration
    - name: Integration tests
      working-directory: gradle-plugin-integration-test
      run: ./gradlew "-Dkotlin.version=${{ matrix.kotlin }}" clean build --stacktrace
